HamkavAuth/urls.py
from django.urls import path
from . import views
from ninja import NinjaAPI
from rest_framework_simplejwt import views as jwt_views

from ninja import Router
# from . ninja_jwt import AuthSchema, JWTPairSchema
from django.contrib.auth import authenticate
from rest_framework_simplejwt.tokens import RefreshToken
# from .api import api

app_name = 'HamkavAuth'

# api = NinjaAPI()     # django-ninja
# @api.get("/add")
# def add(request, a:int , b:int):
#     return {"result": a+b}

# api = NinjaAPI(csrf=True)

# router = Router()

# @router.post('/log', response=JWTPairSchema, auth=None)
# def login(request, auth: AuthSchema):
#     user = authenticate(**auth.dict())
#     if user is not None:
#         refresh = RefreshToken.for_user(user)

#     return {
#         'refresh': str(refresh),
#         'access': str(refresh.access_token),
#     }
    

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name = 'user_register' ),
    path('login/', views.UserLoginView.as_view(), name = 'user_login' ),
    path('logout/', views.UserLogoutView.as_view(), name = 'user_logout' ),
    path('passwordecovery/', views.UserPasswordRecoveryView.as_view(), name = 'user_password_recovery' ),
    path('changepassbyrecovery/', views.UserChangePassword.as_view(), name = 'user_change_password_by_recovery' ),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name = 'verify_code' ),
    
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('edit_user/', views.EditUserView.as_view(), name='edit_user'),
    path('home/', views.HomeView.as_view(), name = 'home' ),
    
    
    
    # django-ninja
    # path("api/", api.urls),
    
    # rest framework
    # path('api/testauth', views.TestAuthView.as_view()),
    # path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    
]

mentolink/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from search import views as search_views

from .api import api


urlpatterns = [
    path("hamkav-admin/", admin.site.urls),
    path("wagtail-admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("search/", search_views.search, name="search"),

    path('accounts/', include('HamkavAuth.urls',namespace='HamkavAuth')),
    path('blog/', include('HamkavBlog.urls',namespace='HamkavBlog')),
    path('edu/', include('HamkavEduShop.urls',namespace='HamkavEduShop')),
    path('db/', include('HamkavDbManagement.urls',namespace='db')),

    path("api/", api.urls),
    
    #  path('markdownx/', include('markdownx.urls')), #Django Markdownx


]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns = urlpatterns + [
        path('__debug__/', include('debug_toolbar.urls')), #django-debug-toolbar
        
    ]



urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

HamkavAuth/forms.py
from django import forms
from .models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import Profile

class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='password', widget=forms.PasswordInput )
    password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput )

    class Meta:
        model = User
        fields = ('email', 'phone_number', 'full_name')

        
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] and cd['password2'] and cd['password1'] != cd['password2']:
            raise ValidationError('passwords dont match') 
        
        return cd['password2']

    def save(self, commit= True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1']) # hashing password before save
        if commit:
            user.save()
        return user
    
    
    
class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField(help_text = "you can change password using <a href = \"../password/\"> this form </a>    ")
    
    class Meta:
        model = User
        fields = ('email', 'full_name', 'password', 'last_login')


class UserRegisterationForm(forms.Form):
    email = forms.EmailField()
    full_name = forms.CharField(label = 'full name')
    phone = forms.CharField(max_length=11)
    password = forms.CharField(widget=forms.PasswordInput)
    
    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email = email).exists()
        if user:
            raise ValidationError('قبلا توسط این ایمیل ثبت نام انجام گرفته است')
        return email
    
    def clean_phone(self):
        phone = self.cleaned_data['phone']
        user = User.objects.filter(phone_number = phone).exists()
        if user:
            raise ValidationError('قبلا توسط این شماره تلفن ثبت نام صورت گرفته است')
        return phone
    
    
class UserLoginForm(forms.Form):
    phone = forms.CharField(max_length=12)    
    password = forms.CharField(widget=forms.PasswordInput)

    # def clean_phone(self):
    #      phone = self.clean_phone['phone']
    #      user = User.objects.filter(phone_number = phone).exists()
    #      if not user:
    #          raise ValidationError('این شماره در د')


class UserPasswordRecoveryForm(forms.Form):
    phone = forms.CharField(max_length=11)    

    def clean_phone(self):
         phone = self.cleaned_data['phone']
         user = User.objects.filter(phone_number = phone).exists()
         if not user:
             raise ValidationError('شماره وارد شده صحیح نمی باشد میتوانید از منوی ثبت نام اقدام به عضویت نمایید')
         return phone
    
    
class UserChangePasswordForm(forms.Form):
    code = forms.IntegerField()
    password = forms.CharField(widget=forms.PasswordInput)    

    # def clean_code(self):
    #      password = self.cleaned_data['password']
    #      user = User.objects.filter(phone_number = phone).exists()
    #      if not user:
    #          raise ValidationError('شماره وارد شده صحیح نمی باشد میتوانید از منوی ثبت نام اقدام به عضویت نمایید')
    #      return phone
     
     
     
    
class EditUserForm(forms.ModelForm):
	email = forms.EmailField()

	class Meta:
		model = Profile
		fields = ('age', 'bio')     
         
class VerifyCodeForm(forms.Form):
    code = forms.IntegerField()
    

HamkavAuth/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect

from django.views import View
from .forms import UserRegisterationForm, UserLoginForm, UserPasswordRecoveryForm, UserChangePasswordForm, VerifyCodeForm, EditUserForm
import random 
from HamkavNotifications.notifs import send_opt_code
from .models import OtpCode, User, Relation
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin

from rest_framework.views import APIView
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework import status
from rest_framework.response import Response
# from serializers import UserSerializer

# API  start ==============
class TestAuthView(APIView):
    # authentication_classes = (authentication.TokenAuthentication,)
    # permission_classes = (permissions.IsAuthenticated,)

    permission_classes = (IsAuthenticated,)
    def get(self, request, format=None):
        return Response("authenticated user!",status=status.HTTP_200_OK)
    
# class CreateUserAPIView(APIView):

#     permission_classes = ()
#     def post(self, request):
#         user = request.data
#         serializer = UserSerializer(data=user)
#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(serializer.data, status=status.HTTP_201_CREATED)


# API end ===================




class ProfileView(View):


    def get(self, request):
        return render(request, 'HamkavAuth/profile.html', {})
    
    
    
class HomeView(View):

    def get(self, request):
        return render(request, 'HamkavAuth/home.html', {})
    
    
    
class UserRegisterView(View):
    form_class = UserRegisterationForm
    template_name = 'HamkavAuth/register.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form':form})
    
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            
            
            
            otpReturn = otpHandle(form.cleaned_data['phone']) # generate and store otp code in db and send for user
            if not otpReturn: # اگر شماره وارد شده شامل غیر عدد و یا طول کمتر از ۱۱ بود
                messages.warning(request, 'شماره تلفن به شکل صحیح وارد نمایید')
                return render(request,self.template_name,{'form':form})
                
            
            # # generate random code and send to user
            # random_code = random.randint(1000,9999)
            # send_opt_code(form.cleaned_data['phone'], random_code)
            
            # # store generated random code in db
            # OtpCode.objects.create(
            #     phone_number = form.cleaned_data['phone'],
            #     code = random_code 
            #     )
            
            #store recived user data in registeration form in session temprory
            request.session['user_registeration_info'] = {
                'phone_number' : form.cleaned_data['phone'],
                'email' : form.cleaned_data['email'],
                'full_name' : form.cleaned_data['full_name'],
                'password' : form.cleaned_data['password'],
            }
            messages.success(request, 'کد احزار هویت برای شما ارسال شد','success')
            return redirect('HamkavAuth:verify_code')
        return render(request,self.template_name,{'form':form})
    
    
class UserRegisterVerifyCodeView(View):
    form_class = VerifyCodeForm
    
    def get(self, request):
        form = self.form_class
        return render(request, 'HamkavAuth/verify_code.html', {'form':form})

    
    def post(self,request):
        user_session = request.session['user_registeration_info']
        code_instance = OtpCode.objects.get(phone_number = user_session['phone_number']) # get otpcode from db
        form = self.form_class(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            # if recived code == sended code then create new user by session info
            if cd['code'] == code_instance.code:
                User.objects.create_user(
                    user_session['phone_number'],
                    user_session['email'],
                    user_session['full_name'],
                    user_session['password'],
                    
                )
                code_instance.delete() # delete sended code from otpcode table
                messages.success(request, ' ثبت نام شما باموفقیت انجام شد لطفا وارد شوید', 'success')
                return redirect('HamkavAuth:user_login')
                # return HttpResponseRedirect('/')
            else:
                messages.error(request, 'کد وارد شده صحیح نمی باشد','danger')
                return redirect('HamkavAuth:verify_code')
    
        messages.error(request, 'ورودی های خود را کنترل کنید در صورت نیاز با پشتیبانی سایت تماس بگیرید.','danger')
        return redirect('HamkavAuth:verify_code')

                 
class UserLoginView(View):
    form_class = UserLoginForm
    template_name = 'HamkavAuth/login.html'
    
    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form':form})
    
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, phone_number = cd['phone'], password = cd['password'])
            if user:
                login(request, user)
                messages.success(request, 'خوش آمدید', 'info')
                return HttpResponseRedirect('/')
                # return HttpResponseRedirect('/blog')
            messages.error(request, 'شماره تلفن یا رمز عبور صحیح نمی باشد', 'warning')
        return render(request, self.template_name, {'form':form})
    

class UserPasswordRecoveryView(View):
    form_class = UserPasswordRecoveryForm
    template_name = 'HamkavAuth/password_recovery.html'    

    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form':form})
    
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = User.objects.filter(phone_number = cd['phone']).exists()
            if user:
                request.session['user_phone_for_recovery'] = {
                'phone_number' : form.cleaned_data['phone'],
                }
                
                # otpHandle(form.cleaned_data['phone']) # generate and store otp code in db and send for user
                otpReturn = otpHandle(form.cleaned_data['phone']) # generate and store otp code in db and send for user
                if not otpReturn: # اگر شماره وارد شده شامل غیر عدد و یا طول کمتر از ۱۱ بود
                    messages.warning(request, 'شماره تلفن به شکل صحیح وارد نمایید')
                    return render(request,self.template_name,{'form':form})
            
                
                messages.success(request, 'کد احزار هویت برای شما ارسال شد','success')
                return redirect('HamkavAuth:user_change_password_by_recovery')
            messages.success(request, 'کاربری با شماره وارد شده یافت نشد','success')
            return redirect('HamkavAuth:user_password_recovery')
        return render(request,self.template_name,{'form':form})
    
    
    
    
                
class UserChangePassword(View):
    form_class =  UserChangePasswordForm
    template_name = 'HamkavAuth/change_password.html'   
    
    def get(self, request):
        form = self.form_class
        return render(request, self.template_name, {'form':form})
        
    def post(self, request):
        user_session = request.session['user_phone_for_recovery']
        # code_instance = OtpCode.objects.get(phone_number = user_session['phone_number'])
        code_instance = OtpCode.objects.filter(phone_number = user_session['phone_number']).last()
        form = self.form_class(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            if cd['code'] == code_instance.code:
                user = User.objects.get(phone_number = user_session['phone_number'])
                user.set_password(cd['password'])
                user.save()
                code_instance.delete()
                messages.success(request, ' کلمه عبور با موفقیت تغییر یافت  لطفا به سیستم وارد شوید', 'success')
                return redirect('HamkavAuth:user_login')
            
            messages.warning(request, ' کد وارد شده صحیح نمی باشد ', 'danger')
            return redirect('HamkavAuth:user_change_password_by_recovery')
        
        return render(request, self.template_name, {'form':form})

                

        

            
            
            # اینجا باید ابتدا در زمان درخواست کد برای کاربر سشن تعریف شود و شماره کاربر در سشن ذخیره شود
            # سپس در این گام سشن بازیابی گردد و باکد ثبت شده مقایسه گردد
            # اگر برابر بود پسورد جدید دریافت و در دیتابیس ذخیره گردد
            
            # user = authenticate(request, phone_number = cd['phone'], password = cd['password'])
            # if user:
            #     login(request, user)
            #     messages.success(request, 'خوش آمدید', 'info')
            #     return HttpResponseRedirect('/')
            # messages.error(request, 'شماره تلفن یا رمز عبور صحیح نمی باشد', 'warning')
        return render(request, self.template_name, {'form':form})   
       
       
       
class EditUserView(LoginRequiredMixin, View):
	form_class = EditUserForm

	def get(self, request):
		form = self.form_class(instance=request.user.profile, initial={'email':request.user.email})
		return render(request, 'HamkavAuth/edit_profile.html', {'form':form})

	def post(self, request):

HamkavAuth/templates/HamkavAuth/partials/login_left.html
{% load static %}
<div class=" col-12 col-lg-6 d-md-flex align-items-center justify-content-center  bg-opacity-10">
    <div class="p-3 p-lg-1 ">
        <!-- Title -->
        <div class="text-center">
            <h2 class="fw-bold fs-3">   ورود به منتولینک </h2>
            <p class="mb-0 h6 fw-light">بیایید امروز چیز جدیدی یاد بگیریم!</p>
        </div>
        <!-- SVG Image -->
        <img src="{% static 'assets/images/element/02.svg' %}" class="mt-5" alt="">
        <!-- Info -->
    </div>
</div>

HamkavAuth/templates/HamkavAuth/partials/login_right.html
{% load static %}


<div class="col-12 col-lg-6 ">
    <div class="row my-2 ">
        <!-- Title -->
        <div class="col-sm-10 col-xl-8 m-auto  shadow-lg border-2 p-4">
            <h3 class="mb-4"> شماره تلفن و رمز عبور   </h3>
        
            <!-- Form START -->
                <form method='post' novalidate>


                {% csrf_token %}


                <!-- phone -->
                <div class="mb-4">
                    <label for="inputPhone" class="form-label"> تلفن</label>
                    <div class="input-group input-group-lg">
                        <span class="input-group-text bg-light rounded-start border-0 text-secondary px-3"><i class="bi bi-envelope-fill"></i></span>
                        <input type="number" name = "phone" class="form-control border-0 bg-light rounded-end ps-1" placeholder="09121111111" id="inputPhone" value = {{ form.phone.value|default_if_none:"" }} >
                    </div>
                    <span class="text-danger">{{form.phone.errors }}</span>


                </div>
                <!-- Password -->
                <div class="mb-4">
                    <label for="inputPassword" class="form-label">رمز عبور *</label>
                    <div class="input-group input-group-lg">
                        <span class="input-group-text bg-light rounded-start border-0 text-secondary px-3"><i class="fas fa-lock"></i></span>
                        <input type="password" name="password" class="form-control border-0 bg-light rounded-end ps-1" placeholder="*********" id="inputPassword">
                    </div>
                    <span class="text-danger">{{form.password.errors }}</span>


                </div>

                <div class="mb-4">
                    <div class="form-check">
                        <input type="checkbox" class="form-check-input" id="checkbox-1">
                        <label class="form-check-label" for="checkbox-1">با ثبت نام <a href="#">شرایط و قوانین سایت</a> را خواهید پذیرفت.</label>
                    </div>
                </div>
                <!-- Button -->
                <div class="align-items-center mt-0">
                    <div class="">
                    {% comment %} <div class="d-grid"> {% endcomment %}
                        <button class="btn btn-primary mb-0" type="submit">ورود </button>
                    </div>
                </div>

            </form>
            <!-- Form END -->


            <!-- Sign in link -->
            <div class="mt-3  text-right">
                <span> آيا در ورود مشکلی دارید؟<a href="{% url 'HamkavAuth:user_password_recovery' %}">  بازیابی رمز عبور </a></span> <br>
                {% comment %} <span> آیا هنوز عضو جامعه منتولینک نشده اید؟<a href="{% url 'HamkavAuth:user_register' %}"> ثبت نام</a></span> {% endcomment %}

                
            </div>

        </div>
    </div>
</div>

HamkavAuth/templates/HamkavAuth/partials/register_left.html
{% load static %}
<div class=" col-12 col-lg-6 d-md-flex align-items-center justify-content-center  bg-opacity-10">
    <div class="p-3 p-lg-1 ">
        <!-- Title -->
        <div class="text-center">
            <h2 class="fw-bold fs-3">  عضویت سریع در منتولینک </h2>
            <p class="mb-0 h6 fw-light">بیایید امروز چیز جدیدی یاد بگیریم!</p>
        </div>
        <!-- SVG Image -->
        <img src="{% static 'assets/images/element/02.svg' %}" class="mt-5" alt="">
        <!-- Info -->
    </div>
</div>

HamkavAuth/templates/HamkavAuth/partials/register_right.html
{% load static %}


<div class="col-12 col-lg-6 ">
    <div class="row my-2 ">
        <!-- Title -->
        <div class="col-sm-10 col-xl-8 m-auto  shadow-lg border-2 p-4">
           
                <!-- Title -->
                
                <h2 class="">ثبت نام</h2>
            
                <!-- Form START -->
                    <form method='post' novalidate>



                    {% csrf_token %}


                  
                    <!-- Email -->
                    <div class="mb-4">
                        <label for="inputEmail" class="form-label">ایمیل</label>
                        <div class="input-group input-group-lg">
                            <span class="input-group-text bg-light rounded-start border-0 text-secondary px-3"><i class="bi bi-envelope-fill"></i></span>
                            <input type="email" name = "email" class="form-control border-0 bg-light rounded-end ps-1" placeholder="***@gmail.com" id="inputEmail" value = {{ form.email.value|default_if_none:"" }}>
                        </div>
                        <span class="text-danger">{{form.email.errors }}</span>

                    </div>
                    <!-- full name -->
                    <div class="mb-4">
                        <label for="inputFullName" class="form-label">نام و نام خانوادگی</label>
                        <div class="input-group input-group-lg">
                            <span class="input-group-text bg-light rounded-start border-0 text-secondary px-3"><i class="bi bi-envelope-fill"></i></span>
                            <input type="text" name = "full_name" class="form-control border-0 bg-light rounded-end ps-1" placeholder="علی حسن زاده" id="inputFullName" value = {{ form.full_name.value|default_if_none:"" }}>
                        </div>
                        <span class="text-danger">{{form.full_name.errors }}</span>


                    </div>
                    <!-- phone -->
                    <div class="mb-4">
                        <label for="inputPhone" class="form-label"> تلفن</label>
                        <div class="input-group input-group-lg">
                            <span class="input-group-text bg-light rounded-start border-0 text-secondary px-3"><i class="bi bi-envelope-fill"></i></span>
                            <input type="number" name = "phone" class="form-control border-0 bg-light rounded-end ps-1" placeholder="09121111111" id="inputPhone" value = {{ form.phone.value|default_if_none:"" }} >
                        </div>
                        <span class="text-danger">{{form.phone.errors }}</span>


                    </div>
                    <!-- Password -->
                    <div class="mb-4">
                        <label for="inputPassword" class="form-label">رمز عبور *</label>
                        <div class="input-group input-group-lg">
                            <span class="input-group-text bg-light rounded-start border-0 text-secondary px-3"><i class="fas fa-lock"></i></span>
                            <input type="password" name="password" class="form-control border-0 bg-light rounded-end ps-1" placeholder="*********" id="inputPassword">
                        </div>
                        <span class="text-danger">{{form.password.errors }}</span>


                    </div>
                    {% comment %} <!-- Confirm Password -->
                    <div class="mb-4">
                        <label for="inputPassword6" class="form-label">تایید رمز عبور *</label>
                        <div class="input-group input-group-lg">
                            <span class="input-group-text bg-light rounded-start border-0 text-secondary px-3"><i class="fas fa-lock"></i></span>
                            <input type="password" class="form-control border-0 bg-light rounded-end ps-1" placeholder="*********" id="inputPassword6">
                        </div>
                    </div> {% endcomment %}
                    <!-- Check box -->
                    <div class="mb-4">
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="checkbox-1">
                            <label class="form-check-label" for="checkbox-1">با ثبت نام <a href="#">شرایط و قوانین سایت</a> را خواهید پذیرفت.</label>
                        </div>
                    </div>
                    <!-- Button -->
                    <div class="align-items-center mt-0">
                        <div class="">
                        {% comment %} <div class="d-grid"> {% endcomment %}
                            <button class="btn btn-primary mb-0" type="submit">ثبت نام</button>
                        </div>
                    </div>

                </form>
                <!-- Form END -->



        </div>
    </div>
</div>