HamkavAuth/urls.py
from django.urls import path
from . import views
from ninja import NinjaAPI
from rest_framework_simplejwt import views as jwt_views

from ninja import Router
# from . ninja_jwt import AuthSchema, JWTPairSchema
from django.contrib.auth import authenticate
from rest_framework_simplejwt.tokens import RefreshToken
# from .api import api

app_name = 'HamkavAuth'

# api = NinjaAPI()     # django-ninja
# @api.get("/add")
# def add(request, a:int , b:int):
#     return {"result": a+b}

# api = NinjaAPI(csrf=True)

# router = Router()

# @router.post('/log', response=JWTPairSchema, auth=None)
# def login(request, auth: AuthSchema):
#     user = authenticate(**auth.dict())
#     if user is not None:
#         refresh = RefreshToken.for_user(user)

#     return {
#         'refresh': str(refresh),
#         'access': str(refresh.access_token),
#     }
    

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name = 'user_register' ),
    path('login/', views.UserLoginView.as_view(), name = 'user_login' ),
    path('logout/', views.UserLogoutView.as_view(), name = 'user_logout' ),
    path('passwordecovery/', views.UserPasswordRecoveryView.as_view(), name = 'user_password_recovery' ),
    path('changepassbyrecovery/', views.UserChangePassword.as_view(), name = 'user_change_password_by_recovery' ),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name = 'verify_code' ),
    
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('edit_user/', views.EditUserView.as_view(), name='edit_user'),
    path('home/', views.HomeView.as_view(), name = 'home' ),
    
    
    
    # django-ninja
    # path("api/", api.urls),
    
    # rest framework
    # path('api/testauth', views.TestAuthView.as_view()),
    # path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    # path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    
]

HamkavBlog/urls.py
from django.urls import path, re_path
from . import views


app_name = 'HamkavBlog'
urlpatterns = [
	path('', views.HomeListView.as_view(), name='home'),
	# path('', views.HomeView.as_view(), name='home'),
	path('post/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
	# path('post/<int:post_id>/<slug:post_slug>/', views.PostDetailView.as_view(), name='post_detail'),
	re_path(r'post/(?P<post_id>[0-9]+)/(?P<post_slug>[-\w]+)/', views.PostDetailView.as_view(), name='post_detail'),
	path('post/delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
	path('post/update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
	path('post/create/', views.PostCreateView.as_view(), name='post_create'),
	path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name='add_reply'),
	path('like/<int:post_id>/', views.PostLikeView.as_view(), name='post_like'),
]

mentolink/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from search import views as search_views

from .api import api


urlpatterns = [
    path("hamkav-admin/", admin.site.urls),
    path("wagtail-admin/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("search/", search_views.search, name="search"),

    path('accounts/', include('HamkavAuth.urls',namespace='HamkavAuth')),
    path('blog/', include('HamkavBlog.urls',namespace='HamkavBlog')),
    path('edu/', include('HamkavEduShop.urls',namespace='HamkavEduShop')),
    path('db/', include('HamkavDbManagement.urls',namespace='db')),

    path("api/", api.urls),
    
    #  path('markdownx/', include('markdownx.urls')), #Django Markdownx


]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    urlpatterns = urlpatterns + [
        path('__debug__/', include('debug_toolbar.urls')), #django-debug-toolbar
        
    ]



urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),
    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

HamkavBlog/models.py
from .wagtail_models import *
from .wagtail_forms import *

# Create your models here.
from django.db import models
from HamkavAuth.models import User
from django.urls import reverse
# from wagtail.fields import RichTextField
from markdownx.models import MarkdownxField
from django.utils.text import slugify

import re

from treebeard.mp_tree import MP_Node
import locale
import jdatetime
from taggit.managers import TaggableManager


class Category2(MP_Node):
    name = models.CharField(max_length=30)

    node_order_by = ['name']

    def __str__(self):
        return '{}'.format(self.name)


class Category(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_category')
	slug = models.SlugField(null=False, blank=False)
	name = models.CharField(max_length=100, null=True, blank=True)
	label = models.CharField(max_length=100, null=True, blank=True)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
 
	def __str__(self):
		return f'{self.slug} - {self.label} - {self.user}'

	def get_absolute_url(self):
		return reverse("HamkavBlog:category_detail", args=(self.id, self.slug))
	



class Post(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='posts')
	category = models.ForeignKey(Category,null=True, on_delete=models.CASCADE, related_name='category_post')
	category2 = models.ForeignKey(Category2,null=True, on_delete=models.CASCADE, related_name='category2_post')
	# body2 =   MarkdownxField(null=True)
	body = models.TextField(null=True)
	brife = models.CharField(max_length=300, null=True, blank=True)
	slug = models.SlugField(null=False, blank=False, editable=False)
	title = models.CharField(max_length=100) 
	tags = TaggableManager()
	is_published = models.BooleanField(default=True) # آيا این پست منتشر شده است یاتنها ذخیره شده
	is_restricted = models.BooleanField(default=False) # آیا دسترسی خاصی برای این مقاله تعیین شده است؟
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	created_shamsi = models.CharField(max_length=50, null=True, editable=False)
	updated_shamsi = models.CharField(max_length=50, null=True, editable=False)
	is_deleted = models.BooleanField(null=True)
	

	class Meta:
		ordering = ['-created']
  
	def __str__(self):
		return f'{self.slug} - {self.updated} - {self.user}'

	def get_absolute_url(self):
		return reverse('HamkavBlog:post_detail', args=(self.id, self.slug))

	def likes_count(self):
		return self.pvotes.count()

	def user_can_like(self, user):
		user_like = user.uvotes.filter(post=self)
		if user_like.exists():
			return True
		return False
    
	def brife_of_body(self):
		return  re.sub('[!?*\[\]#(.*?\)|\[.*?\]=-_]',"",self.body[:200]) [:300]

	def post_preview(self):
		return self.body[:600]  # usefull when post is restricted

	# def delete_post(self):
		

	

	def save(self,  *args, **kwargs):
		self.brife = self.brife_of_body()
		self.slug = slugify(self.title[:50], allow_unicode=True)
		# locale.setlocale(locale.LC_ALL, "fa_IR")
		# jdatetime.set_locale('fa_IR')
		self.created_shamsi = jdatetime.datetime.now().strftime("%a, %d %b %Y %H:%M:%S")
		# self.created_shamsi = jdatetime.datetime.now().strftime("%a, %d %b %Y %H:%M:%S")
		super(Post, self).save( *args, **kwargs)

class Comment(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomments')
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomments')
	reply = models.ForeignKey('self', on_delete=models.CASCADE, related_name='rcomments', blank=True, null=True)
	is_reply = models.BooleanField(default=False)
	body = models.TextField(max_length=400)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f'{self.user} - {self.body[:30]}'



class Vote(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='uvotes')
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pvotes')

	def __str__(self):
		return f'{self.user} liked {self.post.slug}'

HamkavBlog/forms.py
from django import forms
from .models import Post, Comment, Category2
from treebeard.forms import movenodeform_factory, MoveNodeForm

# from markdownx.fields import MarkdownxFormField

class CategoryForm(MoveNodeForm):
    class Meta:
        model = Category2
        exclude = ('sib_order', 'parent')
        
class PostCreateUpdateForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('body','title', 'category2', 'is_published' )
		labels = {
            'category2': 'دسته بندی',
            'is_published': ' پست منتشر شود؟',
        }
		widgets = {
			'body': forms.Textarea(attrs={'id':'markdown_input' , 'class':'form-control shadow-lg'}),
			'category2': forms.Select(attrs={'class':'form-control shadow-lg'}),
			'title': forms.TextInput(attrs={'class':'form-control shadow-lg'}),
			# 'is_published': forms.BooleanField(),
			# 'title': forms.TextInput(attrs={'class':'form-control shadow-lg'}),
		}


class CommentCreateForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('body',)
		widgets = {
			'body': forms.Textarea(attrs={'class':'form-control'})
		}


class CommentReplyForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('body',)


class PostSearchForm(forms.Form):
	search = forms.CharField()

HamkavBlog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
# from django.views.generic import ListView
from .models import Post, Comment, Vote, Category2
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from .forms import PostCreateUpdateForm, CommentCreateForm, CommentReplyForm, PostSearchForm, CategoryForm
from django.utils.text import slugify
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from markdownx.utils import markdownify
from django.core.paginator import Paginator


# class HomeView(View):
# 	form_class = PostSearchForm

# 	def get(self, request):
# 		posts = Post.objects.all()
# 		if request.GET.get('search'):
# 			posts = posts.filter(body2__contains=request.GET['search'])
# 		return render(request, 'HamkavBlog/index.html', {'posts':posts, 'form':self.form_class})


class HomeListView(View):
	form_class = PostSearchForm
    
    
	def get(self, request):
		posts = Post.objects.filter(is_deleted = None, is_published = True )
		if request.GET.get('search'):
			posts = posts.filter(body__contains=request.GET.get('search'))
		paginator = Paginator(posts, 16)
		page_number = request.GET.get('page')
		page_obj = paginator.get_page(page_number)
		return render(request, 'HamkavBlog/index.html', {'posts':page_obj, 'form':self.form_class})


class AllUserPostView(View):
	form_class = PostSearchForm
    
	def get(self, request):
		posts = Post.objects.filter(user = request.user)
		if request.GET.get('search'):
			posts = posts.filter(body__contains=request.GET.get('search'))
		paginator = Paginator(posts, 16)
		page_number = request.GET.get('page')
		page_obj = paginator.get_page(page_number)
		return render(request, 'HamkavBlog/index.html', {'posts':page_obj, 'form':self.form_class})



class PostDetailView(View):
	form_class = CommentCreateForm
	form_class_reply = CommentReplyForm

	def setup(self, request, *args, **kwargs):
		self.post_instance = get_object_or_404(Post, pk=kwargs['post_id'], slug=kwargs['post_slug'], is_deleted = None)
  
		return super().setup(request, *args, **kwargs)

	def get(self, request, *args, **kwargs):
		comments = self.post_instance.pcomments.filter(is_reply=False)
		can_like = False
		if request.user.is_authenticated and self.post_instance.user_can_like(request.user):
			can_like = True
   
		
			
      
   
		if not request.user.is_authenticated:
			self.post_instance.body = self.post_instance.post_preview()+'.....(جهت مشاهده ادامه این مقاله لطفا وارد شوید)'
		if request.user.is_authenticated and self.post_instance.is_restricted:
			self.post_instance.body = self.post_instance.post_preview()+'.....(جهت مشاهده ادامه این مقاله لطفا عضو ویژه منتولینک شوید)'
      
			
   
   
		# self.post_instance.body2 = markdownify(self.post_instance.body2)
		# print(self.post_instance.body)
		return render(request, 'HamkavBlog/detail.html', {'post':self.post_instance, 'comments':comments, 'form':self.form_class, 'reply_form':self.form_class_reply, 'can_like':can_like})

	@method_decorator(login_required)
	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST)
		if form.is_valid():
			new_comment = form.save(commit=False)
			new_comment.user = request.user
			new_comment.post = self.post_instance
			new_comment.save()
			messages.success(request, ' پاسخ شما ثبت شد. ', 'success')
			return redirect('HamkavBlog:post_detail', self.post_instance.id, self.post_instance.slug)


class PostDeleteView(LoginRequiredMixin, View):
	def get(self, request, post_id):
		post = get_object_or_404(Post, pk=post_id)
		if post.user.id == request.user.id:
			# post.delete()   # حذف فیزیکی
			post.is_deleted = True
			post.save() #حذف منطقی 
			messages.success(request, ' پست مورد نظر شما حذف شد ',  'success')
		else:
			messages.error(request, 'شما نمی توانید این پست را حذف کنید', 'danger')
		return redirect('HamkavBlog:home')


class PostUpdateView(LoginRequiredMixin, View):
	form_class = PostCreateUpdateForm
	template_name = 'HamkavBlog/update.html'
 

	def setup(self, request, *args, **kwargs):
		self.post_instance = get_object_or_404(Post, pk=kwargs['post_id']) 
   
		return super().setup(request, *args, **kwargs)

	def dispatch(self, request, *args, **kwargs):
		post = self.post_instance
		if not post.user.id == request.user.id:
			messages.error(request, 'شما نمی توانید این پست را ویرایش کنید', 'danger')
			return redirect('HamkavBlog:home')
		return super().dispatch(request, *args, **kwargs)

	def get(self, request, *args, **kwargs):
		post = self.post_instance
  
		form = self.form_class(instance=post)
		# print(form.is_published)
		return render(request, self.template_name, {'form':form, 'is_published':post.is_published})

	def post(self, request, *args, **kwargs):
		post = self.post_instance
		form = self.form_class(request.POST, instance=post)
		if form.is_valid():
			new_post = form.save(commit=False)
			# new_post.slug = slugify(form.cleaned_data['body'][:30])
			new_post.save()
			messages.success(request, 'پست شما با موفقیت به روز شد', 'success')
			return redirect('HamkavBlog:post_detail', post.id, post.slug)
		messages.warning(request,'اشکالی در اطلاعات ارسالی وجود دارد لطفا ورودی ها کنترل نمایید.' )
		return render(request, self.template_name, {"form":form})


class PostCreateView(LoginRequiredMixin, View):
	form_class = PostCreateUpdateForm
	template_name = 'HamkavBlog/create.html'

	def get(self, request, *args, **kwargs):
		form = self.form_class
		# tree = Category2.dump_bulk()
		# tree = Category2.get_annotated_list()
		tree = Category2.get_tree(parent=None)
		# branch = Category2.dump_bulk(node_obj)
		return render(request, self.template_name, {'form':form, 'category2':tree})

	def post(self, request, *args, **kwargs):
		form = self.form_class(request.POST)
		if form.is_valid():
			new_post = form.save(commit=False)
			# new_post.slug = slugify(form.cleaned_data['body2'][:30])
			new_post.user = request.user
			new_post.save()
			messages.success(request, 'پست شما به زودی منتشر میشود', 'success')
			return redirect('HamkavBlog:post_detail', new_post.id, new_post.slug)
		# print(form)
		messages.warning(request,'اشکالی در اطلاعات ارسالی وجود دارد لطفا ورودی ها کنترل نمایید.' )
		return render(request, self.template_name, {"form":form})

class PostAddReplyView(LoginRequiredMixin, View):
	form_class = CommentReplyForm

	def post(self, request, post_id, comment_id):
		post = get_object_or_404(Post, id=post_id)
		comment = get_object_or_404(Comment, id=comment_id)
		form = self.form_class(request.POST)
		if form.is_valid():
			reply = form.save(commit=False)
			reply.user = request.user
			reply.post = post
			reply.reply = comment
			reply.is_reply = True
			reply.save()
			messages.success(request, 'پاسخ شما ثبت شد.', 'success')
		return redirect('HamkavBlog:post_detail', post.id, post.slug)


class PostLikeView(LoginRequiredMixin, View):
	def get(self, request, post_id):
		post = get_object_or_404(Post, id=post_id)
		like = Vote.objects.filter(post=post, user=request.user)
		if like.exists():
			messages.error(request, 'این پست را لایک کردید!', 'danger')
		else:
			Vote.objects.create(post=post, user=request.user)
			messages.success(request, '\u2764 این پست رو دوست داشتید', 'success')
		return redirect('HamkavBlog:post_detail', post.id, post.slug)

HamkavBlog/templates/HamkavBlog/(delete)blog_tag_index_page.html
{% extends "base.html" %}
{% load wagtailcore_tags %}

{% block content %}

    {% if request.GET.tag %}
        <h4>Showing pages tagged "{{ request.GET.tag }}"</h4>
    {% endif %}

    {% for blogpage in blogpages %}

          <p>
              <strong><a href="{% pageurl blogpage %}">{{ blogpage.title }}</a></strong><br />
              <small>Revised: {{ blogpage.latest_revision_created_at }}</small><br />
              {% if blogpage.author %}
                <p>By {{ blogpage.author.profile }}</p>
              {% endif %}
          </p>

    {% empty %}
        صفحه ای با برچسب انتخاب شده یافت نشد!
    {% endfor %}

{% endblock %}

HamkavBlog/templates/HamkavBlog/blog_base.html
{% extends 'base.html' %}
{% load static %}


{% block extra_css_file%}
<link rel="stylesheet" type="text/css" href="{%  static 'assets/vendor/simplemde/rtl/simplemde-rtl.min.css' %}">
<link rel="stylesheet" type="text/css" href="{%  static 'assets/vendor/simplemde/rtl/simplemde-custom.css' %}">
<link rel="stylesheet" type="text/css" href="{%  static 'assets/vendor/highlights/default.min.css' %}">
{% endblock%}

{% block extra_css %}



<style>
  
    .editor-statusbar .words:before {
        content: 'کلمه: ';
    }

    .editor-statusbar .lines:before {
        content: 'خط: ';
    }
   
		.pagination-primary-soft .page-link {
			border: transparent;
			border-radius: 0.325rem !important;
			color: #000000b8;
			background-color:white
		}

        .pagination-primary-soft .page-item.active .page-link {
            color: var(--bs-white);
            background-color: #000000b8;
        }
        .pagination-primary-soft .page-link:hover {
            z-index: 2;
            color: var(--bs-white);
            background-color: #000000b8;
            border-color: black;
        }

        .markdownview  code
        {
            /*
            border-radius: 0 0 var(--border-radius-medium) var(--border-radius-medium);
            font-family: monospace;
            */
            font-size: 15px;
            overflow-x: auto;
        }








</style>
{% endblock %}

{% block level1_menu%}

{% if request.user.is_authenticated %}
    <li class="nav-item dropdown"><a class="btn btn-primary mb-0 p-1 mt-2" href="{% url 'HamkavBlog:post_create' %}"> نوشتن </a></li>
{% else %}

{% endif %}

{% if request.user.is_admin %}{% endif %} 




{% endblock%}




{% block content %}
<div class="bg-light">
    {% block blog_content %}{% endblock %}
</div>
{% endblock %}





{% block extra_js_file%}
<script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
<script src="{%  static 'assets/vendor/simplemde/rtl/simplemde-rtl.min.js' %}"></script>
<script src="{%  static 'assets/js/simpleMDEconfig.js' %}"></script>
<script src="{%  static 'assets/vendor/highlights/highlight.min.js' %}"></script>


{% endblock%}


{% block extra_js %}
    {% block blog_extra_js %}


     <script>hljs.highlightAll();</script> 
    

    {% endblock %}
{% endblock %}

HamkavBlog/templates/HamkavBlog/create.html
{% extends 'HamkavBlog/blog_base.html' %} {% block blog_content %}

<section class="position-relative pt-3 bg-light">
	<div class="container">

		<div class="mt-5 w-100">


			<form action="" method="post" novalidate>
				{% csrf_token %}
		
				<div class="row mb-lg-3 mb-md-0 mb-sm-0">
					<div class="col-8">
						<label for="title" class="form-label">عنوان نوشته شما:</label>
						{{form.title}}
						<span class="text-danger">{{form.title.errors }}</span>
					</div>
					<div class="col-4">
						<label for="category2" class="form-label">{{form.category2.label}}</label>
						{{form.category2}}
						<span class="text-danger"> {{form.category2.errors}}</span>
					</div>
				</div>
				<div class="row">
					<div class="">
						{% comment %}
						<label for="title" class="form-label">عنوان نوشته شما:</label>
						{% endcomment %}
						<textarea name="body" rows="7" class="form-control" id="markdown_input" placeholder="عنوان...">{{ form.body.value|default_if_none:"" }}</textarea>
						<span class="text-danger">{{form.body.errors }}</span>
					</div>
			  <div>
				{% comment %} {{form.tags}} {% endcomment %}
			  </div>
				</div>

				<div class="d-flex flex-row bd-highlight align-items-center">
					<div class=" bd-highlight">
						<input type="submit" class="mx-3 btn btn-blue" value="ارسال" />
					</div>
					<div class="px-3">
						<div class="form-check-reverse form-switch form-check-lg">
							<label class=" px-2 pt-1 " for="id_published">  انتشار پست:</label>
							<input class=" form-check-input" type="checkbox" name = "is_published" role="switch" id="id_published" >
						</div> 
					</div>
				</div>

		

			
				{% comment %} {{form.is_published	}} {% endcomment %}




			</form>
		</div>

<div>
</section>



{% endblock %} {% block blog_extra_js %}
<script></script>

{% comment %} <script>
	var app = Vue.createApp({
		data() {
			return {
				message: "Ciao",
				class_name: "d-none",
			};
		},
		// for global
		delimiters: ["[[", "]]"],
		// for standalone
		compilerOptions: {
			delimiters: ["[[", "]]"],
		},
	}).mount("#app");
</script> {% endcomment %}

{% endblock %}

HamkavBlog/templates/HamkavBlog/detail.html
{% extends 'HamkavBlog/blog_base.html' %} {% load static %} {% load markdown_processing %} {% comment %} {% load wagtailcore_tags %} {% endcomment %} {% block blog_content %} {% comment %} {% if
request.user.id == post.user.id %}
<a href="{% url 'HamkavBlog:post_delete' post.id %}" class="btn btn-danger">Delete</a>
<a href="{% url 'HamkavBlog:post_update' post.id %}" class="btn btn-info">Update</a>
{% endif %} {% endcomment %}

<!-- =======================
Main Content START -->
<section class="pb-1 pt-6 pb-md-5 bg-white ">
	<div class="container">
		<div class="row">
			<div class="col-lg-10 col-sx-12">
				<!-- Title and Info START -->
				<div class="row">
					<!-- Content -->
					<div class="col-lg-9 order-1">
						<!-- Pre title -->

						{% comment %} <span>{{post.user.full_name}}</span> |<span> {{ post.created|timesince }} پیش</span><span class="mx-2">|</span>
						<div class="badge text-bg-success">{{post.category.label}}</div>
						{% endcomment %}
						<a href="{% url 'HamkavAuth:user_profile' post.user.id %}">{{ post.user.full_name }} <span class="me-3 small text-secondary-emphasis"> | {{ post.created|timesince }} پیش</span></a>
						<div class="badge text-bg-success">{{post.category2}}</div>

						 {% if request.user == post.user %}
						 	{% if post.is_published %}
								<div class="badge text-bg-blue">منتشر شده</div>
								{% else %}
								<div class="badge text-bg-danger">پیش نویش </div>
							{% endif %} 
						{% endif %} 

						<!-- Title -->
						<h1 class="mt-4 mb-4 fs-4">{{post.title}}</h1>
						<div class="fs-5 lh-lg markdownview" style="color:#444444">
							{{post.body|markdown|safe}} {% comment %} {{post.created_shamsi}} {% endcomment %}
						</div>

		{% if not request.user.is_authenticated %}
		<a class="btn btn-primary" href="{% url 'HamkavAuth:user_login' %}?next={{request.path}}"> ورود به منتولینک </a>
		{% endif %}
		{% if post.is_restricted%}
		
		{%endif%}
						{% comment %} <div class="row g-4">
					
							
							<div class="z-index-1 ">
								<!-- Counter item -->
								<div class="">
									<div class="p-4 bg-warning bg-opacity-15 rounded-3">
										
										جهت مشاهده ادامه این پست نیاز است عضو سایت باشید
								این عضویت رایگان و در کمتر از ۳۰ ثانیه انجام میپذیرد
									</div>
								</div>
							</div> 

							
						</div> {% endcomment %}
						


						<div class="pt-3 pb-3">{% include 'HamkavBlog/partials/post_buttons/vertical_controls.html' %}</div>
					</div>
				</div>
				<!-- Title and Info END -->

				<hr />
				<!-- Divider -->

				<!-- Comment review and form START -->
				<div class="row mt-4">
					<!-- Comment START -->
					{% include 'HamkavBlog/partials/comments/comments.html' %}
					<!-- Comment END -->
				</div>
				<!-- Comment review and form END -->
			</div>
			<div class="col-lg-2 d-none d-lg-block">
				<!-- Tags and share START -->
				<div class="mt-3">{% include 'HamkavBlog/partials/tags/tags.html' %}</div>
				<hr />
				<!-- Tags and share END -->
			</div>
		</div>
		<!-- Row END -->
	</div>
</section>
<!-- =======================
Main Content END -->

{% endblock %}

HamkavBlog/templates/HamkavBlog/index.html
{% extends 'HamkavBlog/blog_base.html' %}
{% load static %}


{% block blog_content %}

        {% include "HamkavBlog/partials/banner.html" %}
        {% include "HamkavBlog/partials/post_list_grid.html" %}

{% endblock %}

{% block extra_js %}

        
{% endblock %}